---

- name: Install Windows Updates
  win_updates:
    category_names: "{{ patching_windows_categories }}"
    state: installed
    reboot: "{{ patching_windows_reboot_allowed }}"
    reboot_timeout: "{{ patching_windows_reboot_timeout }}"
  when:  patching_windows_update_allowed
  register: windows_update_result
  changed_when:
    - windows_update_result.installed_update_count is defined
    - windows_update_result.installed_update_count > 0
  failed_when:
    - windows_update_result.failed_update_count is defined
    - windows_update_result.failed_update_count > 0
